### ISSUE TITLE
Incompatibility Identified w/ 'Minimal UI' Module  

### ISSUE THREAD

**Issue by PhluXx1** [jrdstauffer/sidebar-expander#1]
I've identified an Interoperability issue when in use with the [Minimal UI](https://foundryvtt.com/packages/minimal-ui) module ([github URL](https://github.com/saif-ellafi/foundryvtt-minimal-ui)). 

Most of the time when you click on a sidebar icon to expand it, it will both **expand and open a popout at the same time**.

Thanks for making this module it's great, hope you can find an easy and quick fix for this issue.

**Comment by jrdstauffer** [comment]
I'm not seeing this issue w/ only Sidebar Expander and Minimal UI loaded. I've checked this on version 0.8.9 and 9 of foundry.
When you left-click on a tab in the sidebar while it's collapsed it should just expand out the sidebar, **not** open a popout. Are you saying that it's still opening a popout? And you say most of the time ... is it only happening sometimes? 
Perhaps it's another module? Can you try w/ all other modules disabled except for Sidebar Expander and Minimal UI?
Or perhaps it's specific settings in Minimal UI? Can you send me your settings for Minimal UI?

**Comment by PhluXx1** [comment]
> When you left-click on a tab in the sidebar while it's collapsed it should just expand out the sidebar, **not** open a popout. Are you saying that it's still opening a popout?

Yes, when I left-click whilst it's collapsed it expands but ALSO opens a popout. 

I just created a brand new 0.8.9 world using the DnD5e game system. I only enabled Sidebar Expander and the Minimal UI module (plus it's dependency). I'm still getting the exact same problem. And by "most of the time" I mean I used it for like an hour and maybe twice it acted normally.

See the gif below for more info.
![sidebarextender_minimalui_issue](https://user-images.githubusercontent.com/72770484/147586010-acf7a6d0-9f56-40c5-bfe1-6e058806650f.gif)

**Comment by jrdstauffer** [comment]
Thanks for the detailed explanation. I'll look into it.

**Comment by jrdstauffer** [comment]
Still can't replicate this issue. What browser are you using? Do you see any errors in the console? When you de-activate Minimal UI does Sidebar Expander work properly?
Also, maybe try to delete the "sidebar-extender" folder from the modules directory in you and re-install?

**Comment by jrdstauffer** [comment]
Do you see any errors in the console?

**Comment by PhluXx1** [comment]
I just followed your instructions and I'm still getting the same issue.

I've tried Chrome, Firefox, and from within the Foundry client program. I've tested this on both my Windows desktop and laptop.

Also please be advised that I've asked a friend to enable Sidebar Expander and Minimal UI, to test this on their PC and they're also experiencing the same problem. 

I'm not sure what platform you're testing this from but I can assure you it doesn't work. It's been tested from multiple browsers and computers all returning the same issue.

**Comment by jrdstauffer** [comment]
I'm on a Windows machine, run foundry via node.js and use chrome. I'll have one of my friends try it out and see if he's experiencing the same issue.
Did your friend have the Expander module (from Sky-Captain) installed prior to making the change? Did you? I doubt it works but can you try to Ctrl+F5 to force refresh your browser and see if that does anything?
Will continue to try to figure it out.

**Comment by jrdstauffer** [comment]
Good news. My friend is seeing the same issue so now I can attempt to troubleshoot better. It definitely is something in Minimal UI as you reported b/c when he disables it, Sidebar Expander works fine. Still, strange it doesn't do it on my machine. He installed using the standard installation as opposed to the node.js installation so maybe that has something to do w/ it.

**Comment by PhluXx1** [comment]
I'd recommend setting up a virtual machine and testing it there. This will likely expedite the troubleshooting process. Thanks for the help this sounds like a major pain to fix.

> Did your friend have the Expander module (from Sky-Captain) installed prior to making the change? Did you?

My friend never used Expander by Skycaptain. I did but it's disabled.

**Comment by jrdstauffer** [comment]
Update! I found the code in Minimal UI that is causing the issues.
Lines 1148-1156 of minimalui.js:
```
Hooks.once('ready', async function () {
$("#sidebar-tabs > a:nth-child(n)").click(function (eve) {
        if (eve.currentTarget.classList.contains('collapse')) return;
        const tabName = jQuery(eve.currentTarget).attr('data-tab');
        if (ui.sidebar._collapsed) {
            ui.sidebar.activateTab(tabName);
        }
    });
});
```
Commenting this section out allows Sidebar Expander to work as intended. I'll try to contact the dev of Minimal UI and see what this code is for and if we can figure something out.

**Comment by jrdstauffer** [comment]
As a side note, I had already commented that code out on mine which is why I didn't see the issues. There are several modules I have my own tweaks to that I have to manually update as I update the actual module, Minimal UI, being one of them. It's a pain in the ass but I'm pretty particular about certain things and never felt like bothering the devs of those mods to provide functionality that probably would only be just for me.

**Comment by PhluXx1** [comment]
Awesome great job and thanks for the persistence. The Minimal UI dev is pretty responsive so I'm hopeful this will get a quick fix.

**Comment by jrdstauffer** [comment]
From @saif-ellafi:

> That seems to be a very old chunk of code, intended to reopen sidebar applications that are already "active" when the sidebar is collapsed.
> Image you click on the Actor sidebar, and it opens the actor app (floating if sideebar is collapsed), then, if you close it, the actor tab will still remain active, so in Core Foundry, if you click it again, nothing will happen. This hacks it so it reactivates a tab either way.
> There is probably a nicer way to do this, let me know how this conflicts we can figure out something in common.

He indicated that it doesn't appear this section of code is needed in v9, so I have asked if he plans on removing it which will resolve this interoperability issue going forward. As for 0.8.9, I suggest commenting out this section of code (lines 1148-1156) and since Minimal UI version 1.1.8 is locked from updating in 0.8.9 you won't have to worry about ever re-applying changes.

**Comment by jrdstauffer** [comment]
@saif-ellafi confirmed that he will be removing this section of code in his next release of Minimal UI (for Foundry v9). I'm going to add a note to the readme to advise commenting out this section of code in Minimal UI version 1.1.8 (Foundry v0.8.9).

**Comment by PhluXx1** [comment]
@jrdstauffer @saif-ellafi That's good news. Does that mean it still won't work properly in 0.8.9? Would be nice if we got a working version for 0.8.9 since a lot of people won't be moving to v9 for several months.

**Comment by jrdstauffer** [comment]
That would be on Minimal UI to do since there isn't anything I can do on my end to prevent his code from executing which is what  is causing the popouts. If you want you could request this on his repository using the issue I opened or  create another.
https://github.com/saif-ellafi/foundryvtt-minimal-ui/issues/71

**Comment by saif-ellafi** [comment]
Sure, I will patch 0.8.9 as well. Shouldn't be much work. I am travelling now but by tomorrow should be there :)

**Comment by jrdstauffer** [comment]
Thanks @saif-ellafi. Very much appreciated =)

**Comment by PhluXx1** [comment]
@jrdstauffer @saif-ellafi You guys are the best thanks so much.

**Comment by saif-ellafi** [comment]
Hi @jrdstauffer - I have patched Minimal UI 1.1.10 for 0.8.9 and released it. It should work now!

However, for V9 I cannot reproduce this issue. Despite my chunk of code being useless, it also does not spawn any floating windows when sidebar expander is enabled

**Comment by PhluXx1** [comment]
@saif-ellafi When I try to update Minimal UI it fails, tried the manifest URL for the new 0.8.9 and also uninstalled and tried reinstalling it's giving the below error.

![image](https://user-images.githubusercontent.com/72770484/147831689-e9addf12-a155-4430-be06-bbaff629c39d.png)

**Comment by saif-ellafi** [comment]
Sorry about that @PhluXx1 - I have just fixed. The change may take effects after a few minutes. Let me know in a while please!

**Comment by PhluXx1** [comment]
@jrdstauffer @saif-ellafi The issue is now resolved. Thank you both for all of your efforts and help. You're both greatly appreciated, awesome people and are what makes Foundry a great VTT. I look forward to seeing what other modules you bring forward to the community. Happy Holidays and I hope you have an amazing New Year.

**Comment by jrdstauffer** [comment]
Thanks @saif-ellafi for your work to make Sidebar Expander compatible w/ Minimal UI.
Thanks for the kind words @PhluXx1 and hope you have an amazing New Year as well.
