### ISSUE TITLE
Sidebar Expander disables part of the Image Browser functionality

### ISSUE THREAD

**Issue by Brimcon** [jrdstauffer/sidebar-expander#2]
With Sidebar Expander enabled, I cannot swap between User Data and Core Data in the Image Browser, clicking User Data or Core Data does nothing and does not print an error in console.

To reproduce, open an item, attempt to change the icon (Easiest is with an actor and attempting to change the portrait) Then click on User Data or Core Data. 

No other modules enabled.
Foundry Version 9.238
D&D 1.5.6
Sidebar Expander Version 1.0.2
Using Chrome Browser.

**Comment by jrdstauffer** [comment]
Thanks for reporting this! I have a fix ready for version 1.0.3.

**Comment by jrdstauffer** [comment]
I have pushed out Sidebar Expander v1.0.3 which resolves this issue. I'll leave this issue open for 24 hours before closing.
