### ISSUE TITLE
Tabbed Chatlog Compatibility

### ISSUE THREAD

**Issue by ravingdragoon** [jrdstauffer/sidebar-expander#3]
Having this module and Tabbed Chatlog enabled at the same time causes the tabbed chatlog to not properly allow changing tabs. This is not triggering any errors in the dev console, so I don't know why this isn't working.

**Comment by jrdstauffer** [comment]
Might have to do with #2. I'll verify and report back.

**Comment by jrdstauffer** [comment]
It does appear the fix for #2 also fixes this issue as well.

**Comment by jrdstauffer** [comment]
I have pushed out Sidebar Expander v1.0.3 which resolves this issue. I'll leave this issue open for 24 hours before closing.

**Comment by ravingdragoon** [comment]
Looks like it's working. Thanks!
